#!/bin/bash

set -euo pipefail

ln -sf ~/workspace/pkst-home/Brewfile ~/Brewfile
brew bundle

pip3 install neovim

if [[ ! -e ~/.config/nvim ]]; then
  git clone git@github.com:luan/nvim ~/.config/nvim
fi

ln -sf ~/workspace/pkst-home/profile ~/.profile
ln -sf ~/workspace/pkst-home/git-authors ~/.git-authors
ln -sf ~/workspace/pkst-home/gitconfig ~/.gitconfig
touch ~/.gitmessage

if [[ -e ~/.config/nvim/user/plug.vim ]]; then
  rm ~/.config/nvim/user/plug.vim
fi
ln -sf ~/workspace/pkst-home/plug.vim ~/.config/nvim/user/plug.vim

ln -sf ~/workspace/pkst-home/tmux.conf ~/.tmux.conf
if [[ ! -e ~/.tmux/plugins/tpm ]]; then
  mkdir -p ~/.tmux/plugins/tpm
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi

if [[ ! -e ~/workspace/git-hooks-core ]]; then
  git clone https://github.com/pivotal-cf/git-hooks-core.git ~/workspace/git-hooks-core
fi

pushd ~/workspace/git-hooks-core > /dev/null
  git pull
popd

os_name=$(uname | awk '{print tolower($1)}')
curl -o cred-alert-cli \
  "https://s3.amazonaws.com/cred-alert/cli/current-release/cred-alert-cli_${os_name}"
chmod 755 cred-alert-cli
mv cred-alert-cli /usr/local/bin

# Get Ruby on the box
RUBY_VERSION="2.5.1"
if ! rbenv versions --bare | grep -q ${RUBY_VERSION}; then
    rbenv install ${RUBY_VERSION} --keep
fi

rbenv global 2.5.1

# Update all default gems
gem update --system
gem update
gem cleanup

echo "Setup successful!"
